import { writeFile } from 'node:fs/promises';
import { tokenStylesheet } from '../src/ui/design-tokens.ts';
import { format, resolveConfig } from 'prettier';
await writeFile(
  'src/ui/tokens.css',
  await format(
    '/* Generated by npm run tokens:generate. Edit design-tokens.ts. */\n' + tokenStylesheet(),
    { ...(await resolveConfig('src/ui/tokens.css')), parser: 'css' },
  ),
);
